### ISSUE TITLE
What's the mean of 'test' in online.sh

### ISSUE THREAD

**Issue by StevenWang30** [Durant35/SqueezeSeg#3]
```sh
#!/bin/bash

export SUB_TOPIC="/kitti/points_raw"

while test $# -gt 0; do
  case "$1" in
    -h|--help)
      echo "Usage: ./scripts/online.sh [options]"
      echo " "
      echo "options:"
```

Why "test" need to be used there? What's the mean of it?

**Comment by Durant35** [comment]
![image](https://user-images.githubusercontent.com/6770853/38870725-49b0a1de-4281-11e8-887f-3814ffc40dd5.png)

**Comment by Durant35** [comment]
![image](https://user-images.githubusercontent.com/6770853/38870750-5ed0a4b0-4281-11e8-8fc3-2173ea989dbe.png)
