### ISSUE TITLE
parameters in segment_node.py

### ISSUE THREAD

**Issue by StevenWang30** [Durant35/SqueezeSeg#4]
in line 314 in segment_node.py, what's the mean of np.radians(2.)?

        x, y, z, i = velo_points[:, 0], velo_points[:, 1], velo_points[:, 2], velo_points[:, 3]
        d = np.sqrt(x ** 2 + y ** 2 + z**2)
        r = np.sqrt(x ** 2 + y ** 2)
        d[d==0] = 0.000001
        r[r==0] = 0.000001
        phi = np.radians(45.) - np.arcsin(y/r)
        phi_ = (phi/dphi).astype(int)
        phi_[phi_<0] = 0
        phi_[phi_>=512] = 511

        # print(np.min(phi_))
        # print(np.max(phi_))
        #
        # print z
        # print np.radians(2.)
        # print min(np.arcsin(z/d))
        theta = **np.radians(2.)** - np.arcsin(z/d)
        # theta = np.radians(10.)-np.arcsin(z/d)
        # print theta
        theta_ = (theta/dtheta).astype(int)
        # print theta_
        theta_[theta_<0] = 0
        theta_[theta_>=64] = 63

**Comment by Durant35** [comment]
long time no reply...
