### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by StevenWang30** [Durant35/SqueezeSeg#5]
I used the segment parts and find the program breaks down while running, with no error when compile it.

And I used gdb to debug, find the error information:

Program received signal SIGSEGV, Segmentation fault.
0x00007fffef78ea70 in boost::math::lanczos::lanczos_initializer<boost::math::lanczos::lanczos17m64, long double>::init::init() ()
   from /usr/lib/libpcl_sample_consensus.so.1.7

I search it in internet and find someone says that which is because the boost conflict with compile_options(-std=c++11).

So what can I do to fix it?

**Comment by Durant35** [comment]
Are you serious with this repository？Are you talking about the lidartld package？

**Comment by StevenWang30** [comment]
Yeah, and I found that if I add "lidartld/segmenters/ground_plane_fitting_segmenter.cpp" in the CMakeLists, the program will break down with segmentation fault.

**Comment by Durant35** [comment]
Was moved to the right repo...
