### ISSUE TITLE
Do I need to train and create SavedModel first?

### ISSUE THREAD

**Issue by tigerk0430** [Durant35/SqueezeSeg#6]
https://github.com/Durant35/SqueezeSeg/blob/e5820c91c01c0549d0caf5148349d92a335ebeda/pcm2pcm.py#L208

hello,
thanks in advance for such a nice code.

I tried to visualize prediction online data from SqueezeSeg model with code I wrote, 
but I think It's a bit slower than I thought. 
It's 3~4 Hz to use ROS & SqueezeSeg and I used your *pcm2pcm.py* and It shows 7~10 Hz which is nice.

but when I run your code *pcm2pcm.py* with my own velodyne data, value *l* shows me jusy 0.

do I have to train model and create *SavedModel* first to use yours code? thank you :-)

**Comment by Durant35** [comment]
Hi. That branch is from my teammate, as mentioned in 
> ![image](https://user-images.githubusercontent.com/6770853/40100610-1c4d7ba2-5917-11e8-8b57-4c87c3448ba7.png)

Just a simple implementation for `master` branch, then higher frequency.

Besides, I'm not sure about his parameters in `squeeze_seg/saved` work or not, recommend you to train your own parameters using his simple-version **squeeze_seg**.

**Comment by tigerk0430** [comment]
I got it 
should train my own parameter first.
thank you :-)
