### ISSUE TITLE
Unknown command line flag 'sub_topic'

### ISSUE THREAD

**Issue by sangych** [Durant35/SqueezeSeg#7]
Thanks for your share ! It caused an error when I run the online.sh , 
my command is : _./scripts/online.sh -sub_topic /velodyne_points_ ,the 'velodyne_points' was my pointcloud topic name
error msg was shown below:
HOSTNAME
=======
ubuntu-16
Waiting for roscore ready...
Press any key to continue!
Traceback (most recent call last):
  File "./src/online.py", line 50, in <module>
    FLAGS=FLAGS)
  File "/home/sang/SqueezeSeg/src/nodes/segment_node.py", line 106, in __init__
    os.environ['CUDA_VISIBLE_DEVICES'] = FLAGS.gpu
  File "/home/sang/tfenv/local/lib/python2.7/site-packages/tensorflow/python/platform/flags.py", line 84, in __getattr__
    wrapped(_sys.argv)
  File "/home/sang/tfenv/local/lib/python2.7/site-packages/absl/flags/_flagvalues.py", line 632, in __call__
    name, value, suggestions=suggestions)
absl.flags._exceptions.UnrecognizedFlagError: Unknown command line flag 'sub_topic'

**Comment by sangych** [comment]
would please help me

**Comment by sangych** [comment]
I added a line in online.py and the issue was solved.
tf.app.flags.DEFINE_string('sub_topic', '/velodyne_points', """subcribed pointcloud topic.""")

**Comment by sangych** [comment]
I added a line in online.py and the issue was solved.
tf.app.flags.DEFINE_string('sub_topic', '/velodyne_points', """subcribed pointcloud topic.""")

**Comment by MoonWolf9067** [comment]
@sangych Hi! Did you run the command online.sh successfully？When I run it, I have encountered the following problem. It stopps running and there is no result in rviz. I am looking forward to your reply.
![5](https://user-images.githubusercontent.com/22995934/48344056-01489780-e6af-11e8-88e7-4c52585d4ad9.png)

**Comment by Durant35** [comment]
@sangych Hope the updated version could solve your problem.

**Comment by sangych** [comment]
@Durant35 Thanks! But I am still confused with this issue, why the arg --sub_topic appeared twice,  both in parser and FLAGS,  different  from the other args in paser.
