### ISSUE TITLE
rviz error: Couldn't find an AF_INET address for []

### ISSUE THREAD

**Issue by kxhit** [Durant35/SqueezeSeg#9]
Hi! I got an error 'Couldn't find an AF_INET address for []' when I add depth_map to rviz. Do you know how to solve it? Thanks!!!

**Comment by Durant35** [comment]
Please upload a screenshot for your error？or just Google it. That’s common

**Comment by kxhit** [comment]
@Durant35 
Thanks! I figure this out by updating my ROS.
